version: "3.8"
services:
  db:
    build: ./database
    container_name: database
    ports:
      - 3306:3306
    volumes:
      - my-datavolume:/var/lib/mariadb
  web_app:
    build: ./web_app
    container_name: web_app
    ports:
      - 5000:5000
    depends_on:
      - "db"
    links:
      - "db:database"
volumes:
  my-datavolume: