version: "3"
services:
  db:
    build: ./Docker/database
    container_name: database
    volumes:
      - my-datavolume:/var/lib/mariadb
  web_app:
    build: ./Docker/web_app
    container_name: web_app
    ports:
      - 5000:5000
    depends_on:
      - "db"
    links:
      - "db:database"
volumes:
  my-datavolume: