apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: nourryx/tp-infra_database
          name: database
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mariadb
              name: my-datavolume
      restartPolicy: Always
      volumes:
        - name: my-datavolume
          persistentVolumeClaim:
            claimName: my-datavolume
