apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: web-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: nourryx/tp-infra_web-app
          name: web-app
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
